from __future__ import annotations

DEFAULT_CONFIG: dict[str, object] = {
    "tg_session_path": "./var/data/session.session",
    "main_channel_index": 0,
    "channel_sharding_mode": "",
    "cache_dir": "./var/cache",
    "download_dir": "",
    "show_thumbnails": True,
    "fetch_thumbnails": True,
    "ui_icon_size": 56,
    "chunk_size_mb": 32,
    "concurrency": 6,
    "caption_prefix": "FC1|",
    "scan_search": "FC1|",
    "use_sha_as_key": True,
    "max_active_jobs": 8,
    "download_integrity_mode": "strict",
    "keep_partial_on_failure": True,
    "upload_compression_mode": "auto",
    "upload_limit_safety_mb": 100,
    "balanced_part_sizing_enabled": True,
    "balanced_part_min_file_mb": 512,
    "balanced_part_target_regular_mb": 1024,
    "balanced_part_target_premium_mb": 2560,
    "small_file_batching_enabled": True,
    "small_file_threshold_kb": 512,
    "small_file_batch_target_mb": 16,
    "small_upload_parallel_jobs": 4,
    "small_batch_mode": "global",
    "small_batch_max_files": 256,
    "small_batch_manifest_mode": "inline_local",
    "send_media_rate_limit": 8.0,
    "get_file_rate_limit": 24.0,
    "upload_throttle_mbps": 0.0,
    "download_throttle_mbps": 0.0,
    "lane_upload_small_max": 4,
    "lane_upload_large_max": 4,
    "lane_download_max": 6,
    "perf_telemetry_window_sec": 1.0,
    "retry": {
        "max_attempts": 6,
        "base_delay": 1.0,
    },
    "crypto": {
        "enabled": False,
        "key_env": "TG_CRYPTO_KEY_B64",
    },
    "api": {
        "enabled": False,
        "host": "127.0.0.1",
        "port": 20451,
        "token": "",
    },
    "cache_max_size_mb": 0,
    "stream_cache_max_mb": 2048,
    "tg_proxy": "",
}
